
service: serverless-go-react-native-backend

provider:
  name: aws
  runtime: provided.al2
  architecture: arm64
  region: ap-northeast-1

plugins:
  - serverless-go-plugin

custom:
  go:
    cmd: GOOS=linux go build -ldflags="-s -w"
    supportedRuntimes: [ "provided.al2" ]
    buildProvidedRuntimeAsBootstrap: true

package:
  individually: true
  exclude:
    - "./**"

functions:
  hello:
    handler: cmd/lambda/main.go
    events:
      - http:
          path: hello
          method: post
