AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Globals: 
  Function:
    Timeout: 10 
    MemorySize: 128
    Runtime: provided.al2
    Architectures:
      - arm64

Resources:
  HelloFunction:
    Type: AWS::Serverless::Function
    Metadata: 
      BuildMethod: go1.x 
    Properties:
      CodeUri: ./
      Handler: cmd/lambda/main.go
      Events:
        HelloApiEvent:
          Type: HttpApi
          Properties:
            Path: /hello
            Method: post

Outputs: 
  HelloApiEndpoint:
    Description: "API Gateway endpoint URL for Hello function"
    Value: !Sub "https://${ServerlessHttpApi}.execute-api.${AWS::Region}.amazonaws.com/hello"
